### ISSUE TITLE
Valetudo map not limited to card size

### ISSUE THREAD

**Issue by DeastinY** [Hypfer/lovelace-valetudo-map-card#146]
Soooo

<img width="349" alt="Screenshot 2023-08-21 at 16 39 18" src="https://github.com/Hypfer/lovelace-valetudo-map-card/assets/5399476/d0914039-d565-49ff-a07a-b92db9e2b9da">

**Comment by DeastinY** [comment]
Happening on Safari and Firefox, I am on MacOS beta, but could recreate on the phone as well.

**Comment by nocalla** [comment]
I'm also seeing this on Firefox on Windows 11 and on the HomeAssistant Android app. 
```
type: custom:valetudo-map-card
vacuum: valetudo_Vacuum
rotate: 270
title: null
show_battery_level: false
show_start_button: false
show_pause_button: false
show_stop_button: false
show_home_button: false
show_locate_button: false
show_status: false
```

![image](https://github.com/user-attachments/assets/95a7cae0-0ce8-459a-bb2d-965d27b63817)

**Comment by mguaylam** [comment]
It would be nice if the min_height was taken into account and the map would expand to the maximum width possible while still being constrained to the card. This would allow good transition between mobile and desktop.

In my case :
```YAML
type: custom:valetudo-map-card
vacuum: valetudo_dreame_w10_appartement
title: Aspirateur
vacuum_icon: mdi:robot-vacuum-variant
map_scale: 1.9
rotate: 270
min_height: 410
```

![Image](https://github.com/user-attachments/assets/bd9c9a1c-dfcc-401d-b045-05fda9a1b45c)
